#!/bin/bash

REDIRECT_URL=${REDIRECT_URL:-"http://example.com"}

sed -i -e "s/rewrite.*/rewrite \^ $(echo $REDIRECT_URL | sed -e 's/[\/&]/\\&/g') permanent;/" /etc/nginx/sites-available/default

exec nginx

